version: '3'

volumes:
  postgres_volumes:
    name: serve-data
    driver: local

services:
  db:
    image: postgres
    container_name: serve-app-db
    ports:
      - "5432:5432"
    restart: always
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
    volumes:
      - "postgres_volumes:/var/lib/postgresql/data"


  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    container_name: serve-app
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
    volumes:
      - .:/my_app
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on: 
      - db
